name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up build environment
        run: apt install libgtk-3-dev cmake make
      
      - name: Set up rxcpp
        run: git clone https://github.com/ReactiveX/RxCpp.git && cd RxCpp && mkdir build && cd build && cmake .. && make && make install

      - name: Build project
        run: make
