name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: update && upgrade
        run: sudo apt update && sudo apt upgrade -y

      - name: Set up build environment
        run: sudo apt install -y qtbase5-dev qt5-qmake cmake libqt5gui5 libqt5widgets5 libqt5core5a

      - name: Build project
        run: |
          qmake
          make
